Update python

diff --git a/bin/steps/python b/bin/steps/python
--- a/bin/steps/python
+++ b/bin/steps/python
@@ -95,14 +95,14 @@ if [[ "$STACK" != "$CACHED_PYTHON_STACK" ]]; then
     rm -rf .heroku/python-stack .heroku/python-version .heroku/python .heroku/vendor .heroku/python .heroku/python-sqlite3-version
 fi
 
-if [ -f .heroku/python-version ]; then
-  if [ ! "$(cat .heroku/python-version)" = "$PYTHON_VERSION" ]; then
-      puts-step "Python version has changed from $(cat .heroku/python-version) to ${PYTHON_VERSION}, clearing cache"
-      rm -rf .heroku/python
-  else
-    SKIP_INSTALL=1
-  fi
-fi
+rm -rf .heroku/python
+# if [ -f .heroku/python-version ]; then
+#   if [ ! "$(cat .heroku/python-version)" = "$PYTHON_VERSION" ]; then
+#       puts-step "Python version has changed from $(cat .heroku/python-version) to ${PYTHON_VERSION}, clearing cache"
+#   else
+#     SKIP_INSTALL=1
+#   fi
+# fi
 
 # If using Pip, check if we should reinstall python dependencies given that requirements.txt
 # is non-deterministic (not all packages pinned, doesn't handle uninstalls etc). We don't need
@@ -120,34 +120,34 @@ if [[ -f "${BUILD_DIR}/requirements.txt" ]]; then
       # Installing Python over again does not take noticably more time
       cp -R "$BUILD_DIR/requirements.txt" "$CACHE_DIR/.heroku/requirements.txt"
       rm -rf .heroku/python
-      unset SKIP_INSTALL
+      # unset SKIP_INSTALL
     else
       puts-step "No change in requirements detected, installing from cache"
     fi
   fi
 fi
 
-if [[ -n "${SKIP_INSTALL}" ]]; then
-  puts-step "Using cached install of ${PYTHON_VERSION}"
-else
-  puts-step "Installing ${PYTHON_VERSION}"
+# if [[ -n "${SKIP_INSTALL}" ]]; then
+#   puts-step "Using cached install of ${PYTHON_VERSION}"
+# else
+# fi
+puts-step "Installing ${PYTHON_VERSION}"
 
-  # Prepare destination directory.
-  mkdir -p .heroku/python
+# Prepare destination directory.
+mkdir -p .heroku/python
 
-  if ! curl --silent --show-error --fail --retry 3 --connect-timeout 5 "${PYTHON_URL}" | tar -zxC .heroku/python; then
-    # The Python version was confirmed to exist previously, so any failure here is due to
-    # a networking issue or archive/buildpack bug rather than the runtime not existing.
-    puts-warn "Failed to download/install ${PYTHON_VERSION}"
-    exit 1
-  fi
-
-  # Record for future reference.
-  echo "$PYTHON_VERSION" > .heroku/python-version
-  echo "$STACK" > .heroku/python-stack
-
-  hash -r
+if ! curl --silent --show-error --fail --retry 3 --connect-timeout 5 "${PYTHON_URL}" | tar -zxC .heroku/python; then
+  # The Python version was confirmed to exist previously, so any failure here is due to
+  # a networking issue or archive/buildpack bug rather than the runtime not existing.
+  puts-warn "Failed to download/install ${PYTHON_VERSION}"
+  exit 1
 fi
+
+# Record for future reference.
+echo "$PYTHON_VERSION" > .heroku/python-version
+echo "$STACK" > .heroku/python-stack
+
+hash -r
 
 PIP_VERSION='22.2.2'
 SETUPTOOLS_VERSION='63.4.3'
